version: "3"

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 443:443
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: basic-realm
    volumes:
      - "./data/registry:/var/lib/registry"
      - "./data/certbot/conf/live/${DOMAIN:?err}/privkey.pem:/certs/domain.key"
      - "./data/certbot/conf/live/${DOMAIN:?err}/fullchain.pem:/certs/domain.crt"
      - "./auth:/auth"

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - "./data/certbot/conf:/etc/letsencrypt"
      - "./data/certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
